language: python
python:
    - "2.7"
before_install:
    - "pip install -r requirements.txt"
install:
    - "python setup.py install"
script:
    - "make test"
notifications:
    email:
        recipients:
            - "ellisonleao@gmail.com"
after_success:
    - coveralls
